name: Kopi
options:
  bundleIdPrefix: com.kopi
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"

targets:
  Kopi:
    type: application
    platform: macOS
    sources:
      - path: Kopi
        excludes:
          - Resources/Assets.xcassets/MenuBarIcon.imageset/menubar_icon.pdf
    resources:
      - path: Kopi/Resources/Assets.xcassets
    info:
      path: Kopi/Resources/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: Kopi
        CFBundleName: Kopi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kopi.app
        PRODUCT_NAME: Kopi
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: Kopi/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: true
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: false
        CODE_SIGN_STYLE: Manual
        SWIFT_STRICT_CONCURRENCY: minimal
    dependencies:
      - package: GRDB
        product: GRDB
    entitlements:
      path: Kopi/Kopi.entitlements
      properties:
        com.apple.security.app-sandbox: false
